// Mocks generated by Mockito 5.3.2 from annotations
// in forms_cubit/test/mock/validator.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:forms_cubit/field/model/field_exception.dart' as _i4;
import 'package:forms_cubit/field/validation/validation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FormsFieldValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockFormsFieldValidator<T> extends _i1.Mock
    implements _i2.FormsFieldValidator<T> {
  @override
  Iterable<_i2.FormsFieldValidatorTriggerType> get triggerTypeList =>
      (super.noSuchMethod(
        Invocation.getter(#triggerTypeList),
        returnValue: <_i2.FormsFieldValidatorTriggerType>[],
        returnValueForMissingStub: <_i2.FormsFieldValidatorTriggerType>[],
      ) as Iterable<_i2.FormsFieldValidatorTriggerType>);
  @override
  bool get hasValidate => (super.noSuchMethod(
        Invocation.getter(#hasValidate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i3.FutureOr<void> validate(T? value) => (super.noSuchMethod(
        Invocation.method(
          #validate,
          [value],
        ),
        returnValueForMissingStub: null,
      ) as _i3.FutureOr<void>);
  @override
  _i3.FutureOr<_i4.FormsFieldException?> onValidate(T? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #onValidate,
          [value],
        ),
        returnValueForMissingStub: null,
      ) as _i3.FutureOr<_i4.FormsFieldException?>);
  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
