name: forms_bloc
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bloc: ">=8.0.0 <9.0.0"
  equatable: ">=2.0.0 <3.0.0"
  meta: ">=1.0.0 <2.0.0"
  async: ">=2.11.0 <3.0.0"

dev_dependencies:
  bloc_test: ">=9.0.0 <10.0.0"
  build_runner: ">=2.0.0 <3.0.0"
  flutter_lints: '>=3.0.0 <4.0.0'
  mockito: ">=5.0.0 <6.0.0"
  test: ">=1.0.0 <2.0.0"