name: forms_cubit
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bloc: ">=8.0.0 <9.0.0"
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  bloc_test: ">=9.0.0 <10.0.0"